### ISSUE TITLE
RH won't launch if MQTT server is not running

### ISSUE THREAD

**Issue by HazardCreative** [ryaniftron/RotorHazard#2]
Without an MQTT server running, during RH startup, server hangs after LED initialization. Then:
```
MQTT broker not alive at '192.168.0.242'
Traceback (most recent call last):
  File "server.py", line 4982, in <module>
    initVRxController()
  File "server.py", line 4980, in initVRxController
    5880,])
  File "C:\Users\Hazard\Documents\GitHub\RotorHazard\src\server\VRxController.py", line 63, in __init__
    subscribe_topics = None)
  File "C:\Users\Hazard\Documents\GitHub\RotorHazard\src\server\VRxCV1_emulator.py", line 46, in __init__
    self.initialize()
  File "C:\Users\Hazard\Documents\GitHub\RotorHazard\src\server\VRxCV1_emulator.py", line 68, in initialize
    raise e
socket.error: [Errno 10060] [Error 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
```

Expected behavior: RH starts up normally, and backgrounds a process to periodically check for MQTT server. A status flag/event is needed for UI notification.

**Comment by ryaniftron** [comment]
Also add a method to check if VRxController is enabled and connected to the broker. Should handle broker going down and back up.

**Comment by HazardCreative** [comment]
Agreed, though I might consider that a separate issue.

**Comment by ryaniftron** [comment]
Added the feature request to #6. This ticket will just capture the bug.

**Comment by ryaniftron** [comment]
Is b014e4b8374b21e95df2634d0350e027c2ebe1f6 what you had in mind? RH is still prevented from running because VRxController is blocking until that completes, but it at least has the logic to wait until connect and retry in failure. Wanna take it from here and just thread VRxController?

**Comment by HazardCreative** [comment]
Expected behavior: RH continues as if not configured for VRxC control, and backgrounds a process to periodically check for MQTT server availability again. A status flag/event is needed for UI notification. 

This also provides a reconnect process that should be used again if RH loses connection with the MQTT server.

A number of groups don't have access to the filesystem or to internet at the field and can't change the config file. If for some reason no MQTT server is available, the timer should not be bricked until the config changes.
