### ISSUE TITLE
Response error if ESP connects without VRx status

### ISSUE THREAD

**Issue by HazardCreative** [ryaniftron/RotorHazard#9]
Steps to reproduce:

- Start RH server and MQTT; wait for stable
- Connect ESP without powering CV

The is unlikely to occur with hardware currently in development, but certainly possible with user-built modules for CV or other integrations. Can also occur if CV is disconnected without ESP disconnect (such as when monitoring ESP serial via USB an unplugging CV).

```
<-RotorHazard: VRxController-> Device CV_D40D7A286F24 is not yet configured by the server after a successful connection. Conducting some config now
<-RotorHazard: clearview.formatter-> Unable to match response '\xe0\xfc\x1c\xfc\xfc\xe0\xfc\xfc\xe0\xfc\x1c\xfc\xfc\xe0\xfc\xfc\xe0\xfc\x1c\xfc\xfc\xe0\xfc\x1c\xfc\xfc\xe0\xfc\xfc\xe0\xfc\xfc\xe0\xfc\xfc\xe0\xfc\xfc183' to any pattern
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\Python27\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\Python27\lib\site-packages\paho\mqtt\client.py", line 3428, in _thread_main
    self.loop_forever(retry_first_connection=True)
  File "C:\Python27\lib\site-packages\paho\mqtt\client.py", line 1782, in loop_forever
    rc = self.loop(timeout, max_packets)
  File "C:\Python27\lib\site-packages\paho\mqtt\client.py", line 1177, in loop
    rc = self.loop_read(max_packets)
  File "C:\Python27\lib\site-packages\paho\mqtt\client.py", line 1568, in loop_read
    rc = self._packet_read()
  File "C:\Python27\lib\site-packages\paho\mqtt\client.py", line 2315, in _packet_read
    rc = self._packet_handle()
  File "C:\Python27\lib\site-packages\paho\mqtt\client.py", line 2952, in _packet_handle
    return self._handle_publish()
  File "C:\Python27\lib\site-packages\paho\mqtt\client.py", line 3228, in _handle_publish
    self._handle_on_message(message)
  File "C:\Python27\lib\site-packages\paho\mqtt\client.py", line 3416, in _handle_on_message
    callback(self, self._userdata, message)
  File "C:\Users\Hazard\Documents\GitHub\RotorHazard\src\server\VRxController.py", line 562, in on_message_resp_targeted
    nt, pattern_response = clearview.formatter.match_response(payload)
TypeError: 'NoneType' object is not iterable
```

**Comment by Ryanf55** [comment]
On the production dongles, the only way they turn on is connected to CV. I don't see this being valid for those. Yes, I absolutely plan to implement a check when ESP boots up of the ClearView's firmware version to display in the UI. During this routine, if there is no response, I can put info on the Web UI that the unit is not responsive to serial. Do you also want MQTT error?

**Comment by HazardCreative** [comment]
Right, likely not an issue on production modules unless there's some CV hardware or software failure. But thinking about user-built modules and ahead to future VRx Control devices, it makes sense to have a check here instead of a crash.

We need to keep MQTT as neutral as possible so it can be used as a channel to communicate with non-VRx devices in the future.

**Comment by HazardCreative** [comment]
No longer an issue.
